
create table num_producto(
	product VARCHAR(250),
	cantidad integer
);

INSERT INTO num_producto(product,cantidad) VALUES
	 ('Bank account or service',86206),
	 ('Checking or savings account',55452),
	 ('Consumer Loan',31604),
	 ('Credit card',89190),
	 ('Credit card or prepaid card',65270),
	 ('Credit reporting',140432),
	 ('Credit reporting, credit repair services, or other personal consumer reports',322817),
	 ('Debt collection',275584),
	 ('Money transfer, virtual currency, or money service',13742),
	 ('Money transfers',5354),
	 ('Mortgage',293191),
	 ('Other financial service',1059),
	 ('Payday loan',5543),
	 ('Payday loan, title loan, or personal loan',11607),
	 ('Prepaid card',3819),
	 ('Student loan',55838),
	 ('Vehicle loan or lease',15040),
	 ('Virtual currency',18);
	
create table num_submitted(
	submitted_via VARCHAR(250),
	cantidad integer
);

INSERT INTO num_submitted(submitted_via,cantidad) VALUES
('Email',408),
('Fax',20281),
('Phone',88128),
('Postal mail',72427),
('Referral',186840),
('Web',1103682);

create table num_anio(
	anio VARCHAR(250),
	cantidad integer
);

INSERT INTO num_anio(anio,cantidad) VALUES
('2011', 2536),
('2012', 72373),
('2013', 108217),
('2014', 153044),
('2015', 168475);

create table num_issue(
	issue VARCHAR(250),
	cantidad integer
);

INSERT INTO num_issue(issue,cantidad) VALUES
	 ('APR or interest rate',5506),
	 ('Account opening, closing, or management',37961),
	 ('Account terms and changes',484),
	 ('Adding money',202),
	 ('Advertising',126),
	 ('Advertising and marketing',2959),
	 ('Advertising and marketing, including promotional offers',3972),
	 ('Advertising, marketing or disclosures',77),
	 ('Application processing delay',540),
	 ('Application, originator, mortgage broker',17229),
	 ('Applied for loan/did not receive money',345),
	 ('Applying for a mortgage',635),
	 ('Applying for a mortgage or refinancing an existing mortgage',5785),
	 ('Arbitration',349),
	 ('Attempts to collect debt not owed',58234),
	 ('Balance transfer',1117),
	 ('Balance transfer fee',221),
	 ('Bankruptcy',448),
	 ('Billing disputes',15136),
	 ('Billing statement',2619),
	 ('Can''t contact lender',1106),
	 ('Can''t contact lender or servicer',317),
	 ('Can''t repay my loan',8726),
	 ('Can''t stop charges to bank account',510),
	 ('Can''t stop withdrawals from your bank account',236),
	 ('Cash advance',245),
	 ('Cash advance fee',196),
	 ('Charged bank acct wrong day or amt',297),
	 ('Charged fees or interest I didn''t expect',2753),
	 ('Charged fees or interest you didn''t expect',3126),
	 ('Closing an account',6094),
	 ('Closing on a mortgage',4699),
	 ('Closing your account',4904),
	 ('Closing/Cancelling account',6389),
	 ('Collection debt dispute',901),
	 ('Collection practices',1001),
	 ('Communication tactics',38557),
	 ('Confusing or misleading advertising or marketing',319),
	 ('Confusing or missing disclosures',526),
	 ('Cont''d attempts collect debt not owed',60682),
	 ('Convenience checks',149),
	 ('Credit card protection / Debt protection',2728),
	 ('Credit decision / Underwriting',5652),
	 ('Credit determination',3057),
	 ('Credit limit changed',59),
	 ('Credit line increase/decrease',2185),
	 ('Credit monitoring or identity protection',4424),
	 ('Credit monitoring or identity theft protection services',3687),
	 ('Credit reporting',1696),
	 ('Credit reporting company''s investigation',16883),
	 ('Customer service / Customer relations',3504),
	 ('Customer service/Customer relations',283),
	 ('Dealing with my lender or servicer',17630),
	 ('Dealing with your lender or servicer',15208),
	 ('Delinquent account',3218),
	 ('Deposits and withdrawals',22851),
	 ('Disclosure verification of debt',30797),
	 ('Disclosures',49),
	 ('Excessive fees',176),
	 ('False statements or representation',22896),
	 ('Fees',232),
	 ('Fees or interest',8221),
	 ('Forbearance / Workout plans',556),
	 ('Fraud or scam',7493),
	 ('Getting a credit card',6304),
	 ('Getting a line of credit',485),
	 ('Getting a loan',1110),
	 ('Getting a loan or lease',1716),
	 ('Getting the loan',759),
	 ('Identity theft / Fraud / Embezzlement',8481),
	 ('Identity theft protection or other monitoring services',399),
	 ('Improper contact or sharing of info',10068),
	 ('Improper use of my credit report',5580),
	 ('Improper use of your report',41348),
	 ('Incorrect exchange rate',68),
	 ('Incorrect information on credit report',102686),
	 ('Incorrect information on your report',198687),
	 ('Incorrect/missing disclosures or info',202),
	 ('Late fee',3639),
	 ('Lender damaged or destroyed property',3),
	 ('Lender damaged or destroyed vehicle',8),
	 ('Lender repossessed or sold the vehicle',79),
	 ('Lender sold the property',7),
	 ('Loan modification,collection,foreclosure',112309),
	 ('Loan payment wasn''t credited to your account',204),
	 ('Loan servicing, payments, escrow account',77333),
	 ('Lost or stolen check',145),
	 ('Lost or stolen money order',150),
	 ('Making/receiving payments, sending money',7404),
	 ('Managing an account',34895),
	 ('Managing the line of credit',806),
	 ('Managing the loan or lease',20664),
	 ('Managing, opening, or closing account',1194),
	 ('Managing, opening, or closing your mobile wallet account',884),
	 ('Money was not available when promised',3360),
	 ('Money was taken from your bank account on the wrong day or for the wrong amount',156),
	 ('Opening an account',5205),
	 ('Other',14779),
	 ('Other features, terms, or problems',8296),
	 ('Other fee',2198),
	 ('Other service issues',514),
	 ('Other service problem',704),
	 ('Other transaction issues',1491),
	 ('Other transaction problem',2706),
	 ('Overdraft, savings or rewards features',53),
	 ('Overdraft, savings, or rewards features',19),
	 ('Overlimit fee',215),
	 ('Payment to acct not credited',461),
	 ('Payoff process',2315),
	 ('Privacy',489),
	 ('Problem adding money',135),
	 ('Problem caused by your funds being low',4526),
	 ('Problem getting a card or closing an account',608),
	 ('Problem when making payments',7535),
	 ('Problem with a company''s investigation into an existing issue',766),
	 ('Problem with a credit reporting company''s investigation into an existing problem',73335),
	 ('Problem with a lender or other company charging your account',4287),
	 ('Problem with a purchase or transfer',1500),
	 ('Problem with a purchase shown on your statement',15768),
	 ('Problem with additional add-on products or services',305),
	 ('Problem with an overdraft',4),
	 ('Problem with cash advance',48),
	 ('Problem with credit report or credit score',8),
	 ('Problem with customer service',620),
	 ('Problem with fraud alerts or security freezes',6909),
	 ('Problem with overdraft',22),
	 ('Problem with the payoff process at the end of the loan',1060),
	 ('Problems at the end of the loan or lease',2876),
	 ('Problems caused by my funds being low',11845),
	 ('Problems when you are unable to pay',9385),
	 ('Property was damaged or destroyed property',3),
	 ('Property was sold',5),
	 ('Received a loan I didn''t apply for',615),
	 ('Received a loan you didn''t apply for',292),
	 ('Repaying your loan',3820),
	 ('Rewards',2916),
	 ('Sale of account',344),
	 ('Settlement process and costs',8940),
	 ('Shopping for a line of credit',302),
	 ('Shopping for a loan or lease',2029),
	 ('Struggling to pay mortgage',22884),
	 ('Struggling to pay your bill',1486),
	 ('Struggling to pay your loan',4983),
	 ('Struggling to repay your loan',5964),
	 ('Taking out the loan or lease',4371),
	 ('Taking/threatening an illegal action',8860),
	 ('Threatened to contact someone or share information improperly',3456),
	 ('Took or threatened to take negative or legal action',12248),
	 ('Transaction issue',2700),
	 ('Trouble during payment process',30486),
	 ('Trouble using the card',1032),
	 ('Trouble using your card',2493),
	 ('Unable to get credit report/credit score',10859),
	 ('Unable to get your credit report or credit score',7118),
	 ('Unauthorized transactions or other transaction problem',967),
	 ('Unauthorized transactions/trans. issues',1325),
	 ('Unexpected or other fees',1195),
	 ('Unexpected/Other fees',103),
	 ('Unsolicited issuance of credit card',1853),
	 ('Using a debit or ATM card',6145),
	 ('Vehicle was damaged or destroyed the vehicle',48),
	 ('Vehicle was repossessed or sold the vehicle',136),
	 ('Was approved for a loan, but didn''t receive money',25),
	 ('Was approved for a loan, but didn''t receive the money',109),
	 ('Written notification about debt',29786),
	 ('Wrong amount charged or received',585);
