version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8050:8050"
    depends_on:
      - database
  database:
    image: 3141618/data_trabajo:v2
    volumes:
      - ./database:/path/to/database  # Ajusta la ruta según la ubicación real de tu base de datos
